### ISSUE TITLE
Support subfield in fields list

### ISSUE THREAD

**Issue by ybennour** [Landoop/kafka-connect-query-language#11]
Such an instruction doesn't work :
`INSERT INTO transactions SELECT field1.subfield1 as column1 FROM topic_A;`

How to map where each subfield in the avro schema will be inserted?

**Comment by johnpaullarsen** [comment]
I've also run into this problem, we have an Avro schema where several fields within a record have a type that is a record (see below).  As far as I can tell we can't use the cassandra sink connector with our Avro schema. Is there any work around? Even flattening the structure or copying it directly into user defined types would be helpful perhaps?

    "name": "Subscriber",
    "namespace": "com.hello.avro",
    "type": "record",
    "doc": "A subscriber is a person, company or other entity that has a business relationship",
    "fields" : [
        {"name": "subscriberId", "type": "SubscriberId", "doc": "The globally unique identifier of the subscriber"},
        {"name": "brandName", "type": "string", "default": "", "doc": "The name of the brand that the subscriber is subscribed to within the set of MyNetFone brands"},
        {"name": "businessName", "type": "string", "default": "", "doc": "The name of the subscribers business where applicable"},
        {"name": "abn", "type": "string", "default": "", "doc": "The Australian Business Number of the subscribers business where applicable"},
        {"name": "businessHoursPhoneNumber", "type": "string", "default": "", "doc": "The business hours phone number of the subscriber"},
        {"name": "afterHoursPhoneNumber", "type": "string", "default": "", "doc": "The after hours phone number of the subscriber"},
        {"name": "primaryRepresentative", "type": "Representative", "doc": "Person who is the primary representative or main contact of the subscriber"},
        {"name": "billingAddress", "type": ["null", "Address"], "doc": "The address that the subscriber is contactable at. Can be null if unknown"},
        {"name": "subscriberStatus", "type": "SubscriberStatus", "default": "ACTIVE", "doc": "The status of the subscriber"}
    ]

**Comment by andrewstevenson** [comment]
Hi @johnpaullarsen, We are looking at adding this, in the meantime what we usually do is add a KStreams job to flatten it or a [Plumber job](https://datamountaineer.com/2016/07/21/kafka-streams-plumber-quick-dirty-processing/)

https://github.com/rollulus/kafka-streams-plumber

**Comment by andrewstevenson** [comment]
@johnpaullarsen The cassandra sink converts the avro to json and uses the json insert functionality of Cassandra, if Cassandra can handle the json insert it should work. Unless you are trying to pull out sub fields in KCQL.

**Comment by andrewstevenson** [comment]
It's something we could probably support in KCQL, I'll chat with the team.

**Comment by sachinkademane** [comment]
Hey everyone!!
Can we use arrays in KCQL queries? Below i have pasted data that need to be put in influxdb.....but i m not getting how to write KCQL for that.... can somebody help me out in doing that?
This data comes as a stream , first array of data comes in 1st second , second array of data comes in the next second ilke that it goes on..
thanks in advance !!

[
 {"timestamp":"2017-10-24T12:44:09.359126933+05:30","namespace":"/intel/procfs/meminfo/high_free","data":0,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-10-24T12:44:09.359385949+05:30"},
 {"timestamp":"2017-10-24T12:44:09.359175426+05:30","namespace":"/intel/procfs/meminfo/low_free","data":0,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-10-24T12:44:09.359390112+05:30"},
 {"timestamp":"2017-10-24T12:44:09.359237088+05:30","namespace":"/intel/procfs/meminfo/shmem","data":35295232,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-10-24T12:44:09.359392144+05:30"},
 {"timestamp":"2017-10-24T12:44:09.359383887+05:30","namespace":"/intel/procfs/meminfo/swap_free","data":29527896064,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-10-24T12:44:09.359394085+05:30"}
]

[
 {"timestamp":"2017-10-24T12:44:39.359971559+05:30","namespace":"/intel/procfs/meminfo/high_free","data":0,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-10-24T12:44:39.360134177+05:30"},
 {"timestamp":"2017-10-24T12:44:39.360018459+05:30","namespace":"/intel/procfs/meminfo/low_free","data":0,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-10-24T12:44:39.360145888+05:30"},
 {"timestamp":"2017-10-24T12:44:39.36008556+05:30","namespace":"/intel/procfs/meminfo/shmem","data":35295232,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-10-24T12:44:39.360148204+05:30"},
 {"timestamp":"2017-10-24T12:44:39.36013247+05:30","namespace":"/intel/procfs/meminfo/swap_free","data":29527896064,"unit":"","tags":{"plugin_running_on":"AELAB110"},"version":4,"last_advertised_time":"2017-10-24T12:44:39.360150028+05:30"}
]

**Comment by Antwnis** [comment]
Closing as this has been long addressed. Array support is not there, and that would require another ticket
