### ISSUE TITLE
Putting data from multiple topics into single Kafka topic

### ISSUE THREAD

**Issue by mananstar2001** [Landoop/kafka-connect-query-language#37]
We are tying to integrate Kafka connector to write to Cassandra. We have multiple topics in which data is coming in, but only partial fields. e.g.

TopicA:
PK1 PK2 C1 C2

TopicB:
PK1 PK2 C3 C4

TopicC:
PK1 PK2 C5 C6

Cassandra Target Table:
PK1 PK2 C1 C2 C3 C4 C5 C6

We want to update all possible columns having same primary key within same row. Right now, it is overwriting the other columns with null values. Also, in our use case we cannot opt for windowing as data arrival sequence is unknown.

Please help.

**Comment by indrajagadeesh** [comment]
hi, 
we are also trying same kind of load to cassandra. do have any solution

thank you

**Comment by andrewstevenson** [comment]
@indrajagadeesh @mananstar2001 Have you looked at `connect.cassandra.default.value` in https://docs.lenses.io/connectors/sink/cassandra.html

**Comment by indrajagadeesh** [comment]
Thank you for responding @andrewstevenson,

this my request body :

{
    "name": "cassandra-sink-orders-16",
    "config": {
    "connector.class": "com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector",
    "connect.cassandra.key.space": "kconnect_sink",
    "tasks.max": "1",
    "connect.cassandra.username": "cassandra",
    "connect.cassandra.password": "cassandra",
    "connect.cassandra.contact.points": "localhost",
    "connect.cassandra.port": "9042",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "connect.cassandra.default.value": "UNSET",
    "connect.cassandra.export.route.query": "INSERT INTO part_table1 SELECT id, last_name AS name, value2 FROM topic2;INSERT INTO part_table1 SELECT id, name, value1 FROM topic1;",
    "topics": "topic2,topic1",
    "value.converter.schema.registry.url": "http://localhost:8083"
    }
}

but, still i am face this issue
![image](https://user-images.githubusercontent.com/39180514/61626448-f3fe9680-ac9a-11e9-94b7-72550856366c.png)

can please help me with proper rest call

**Comment by andrewstevenson** [comment]
@mananstar2001 what version of the connector are you using? You have `connect.cassandra.export.route.query` is very old.

**Comment by indrajagadeesh** [comment]
Hi andrewstevenson,
i am using this version : kafka-connect-cassandra-0.2-3.0.0-all.jar
this my rest body : 

{
    "name": "cassandra-sink-orders-16",
    "config": {
    "connector.class": "com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector",
    "connect.cassandra.key.space": "kconnect_sink",
    "tasks.max": "1",
    "connect.cassandra.username": "cassandra",
    "connect.cassandra.password": "cassandra",
    "connect.cassandra.contact.points": "localhost",
    "connect.cassandra.port": "9042",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "connect.cassandra.default.value": "UNSET",
    "connect.cassandra.export.route.query": "INSERT INTO part_table1 SELECT *, last_name AS name FROM part2 ;INSERT INTO part_table1 SELECT * FROM part1;",
    "topics": "part2, part1",
    "value.converter.schema.registry.url": "http://localhost:8083"
    }
}

can you please provide proper configuration if there is mistake.

**Comment by andrewstevenson** [comment]
@mananstar2001 that's very old and doesn't have this functionality. You should upgrade to the latest, 1.2.2

**Comment by mananstar2001** [comment]
Thanks a lot @andrewstevenson, after upgrade it worked as desired.
